### PR TITLE
Extended NGA test coverage

### PR DESCRIPTION
**Pull request by dfisc**
- Extend NGA test coverage for DVB profile "dvbdash-profile-2017"
- Change schematron file extensions (.sch) to be in line with OxygenXML conventions
- Update to xslt2 and saxon9he to support user defined xslt functions and improve modularity
  - Adapt validator app accordingly and re-compile sources
  - Adapt "caller" php code

### CODE REVIEW

**Comment by eceozturk** [comment]
Thank you for this work. I was testing this version with our existing test vectors and I encountered some wrong "Validation fail" cases.

An example is: 
- MPD URL: http://dash.akamaized.net/dash264/TestCases/2a/qualcomm/1/MultiResMPEG2.mpd
- Error statement: "The value of the width attribute shall be in the range defined by the AdaptationSet."
- Problem: All the width values in the Representations are actually less than or equal to maxWidth value in the Adaptation Set. So, this error should not come up.

There were similar errors like this for profile and codec checks. So, at this moment we cannot merge this PR. However, I will leave it open for the possible commits fixing these issues.

**Comment by wschidol** [comment]
The error is caused by comparisons being done as string comparisons rather than numerical comparisons. I am not sure why this error is exposed by our changes as we have not changed anything regarding these specific tests.

Anyhow, I'll follow up with a patch that resolves this problem.

**Comment by wschidol** [comment]
This latest commit should fix that particular issue. Do you have a standard regression suite that you run all PRs through? We could check with the latest changes.

**Comment by eceozturk** [comment]
Thank you for the fix. This removed the error with maxWidth comparison, however there are two new errors that I noticed:

1. When framerate attribute is like 24000/1001 or 30000/1001, the int comparison fails with "error evaluating framerate"
Example URL: https://dash.akamaized.net/dash264/TestCases/6c/envivio/manifest.mpd

2. The test in SegmentTimeline element also fails with "error evaulating (S/@d): A sequence of more than one item is not allowed as the first operand of 'div'"
Example URL: https://dash.akamaized.net/dash264/TestCases/6b/microsoft/CENC_HD_Time/CENC_HD_time_MPD.mpd

I am not sure if the second error is something that is caused by the fix or something that has always been there without us noticing it and somehow got triggered with the fix. If the latter, please let us know and in such a case you do not have to prepare a fix for this. 

- An additional thing would be the removal of informational reporting for the schematron validation that comes with <svrl:schematron-output>. It currently prints out all the titles in the testing such as in the figure below, and the output becomes a bit confusing.

image

**Comment by wschidol** [comment]
I believe that both of the errors you report have always been in the codebase. Taking the first one as example, @frameRate can be fractional but the codebase contained no code to deal with this.
That said, we have supplied fixes; would appreciate your review.

Re: "removal of informational reporting" I am not sure what you refer to. Do you mean the additional information in https://github.com/Dash-Industry-Forum/DASH/pull/33/commits/0953eaebc8f1dcd59de0cbc4d8883c100f9946fd#diff-2069e3d0336400b0878ca4635da9b88e ? I believe that that output is accurate as it reflects the additional tests that are performed. Are you saying that the output is inaccurate? In any case, this output is not something that seems to be exposed to users of the conformance frontend, so I am not sure it is worth investing in changes here.

**Comment by eceozturk** [comment]
I checked the current code and you were indeed right that these were bugs from the mpdvalidator. Thanks for fixing them nevertheless. 

Regarding the informational reporting, the information there is correct. But there was something wrong with my build. So, please ignore this one and I apologize for the inconvenience. 

I merged the PR.

**Pull request merged**
